name: Build Jekyll Site

on:
  push:
    branches:
      - main  # Runs the workflow when changes are pushed to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Python Dependencies
    - name: Install Python Dependencies
      run: |
        if [ -f requirements.txt ]; then
          python -m venv /github/workspace/myenv
          source /github/workspace/myenv/bin/activate
          pip install -r requirements.txt
        else
          echo "No requirements.txt file found, skipping Python dependencies installation."
        fi

    # Step 4: Set Up Ruby and Jekyll
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  
        bundler-cache: true  
    # Step 5: Build Jekyll Site
    - name: Build Jekyll Site
      run: |
        bundle install
        bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    # Step 6: Verify Build Output
    - name: Check Build Output
      run: ls -l ./_site
